version: '3'

services:

  client:
    image: nouman95/frontend
  
  backend:
    image: nouman95/backend
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGPORT=${PGPORT}
    expose:
      - 5000
  worker:
    image: nouman95/worker
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

  nginx:
    image: nouman95/nginx
    ports:
      - "80:80"
    depends_on:
      - backend
