name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build images
        run: |
          docker build -t nouman95/backend ./backend
          docker build -t nouman95/frontend ./frontend
          docker build -t nouman95/nginx ./nginx
          docker build -t nouman95/worker ./worker


      - name: Push images
        run: |
          docker push nouman95/backend
          docker push nouman95/frontend
          docker push nouman95/nginx
          docker push nouman95/worker

      - name: Generate deployment package
        run: zip -r deploy.zip Dockerrun.aws.json

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          application_name: docker multi
          environment_name: dockermulti-env
          version_label: v-${{ github.sha }}
          region: us-east-1
          deployment_package: deploy.zip
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}